### ISSUE TITLE
Component Group edits need to be relative not exact

### ISSUE THREAD

**Issue by PuReAdDicT** [zegreatclan/AssettoCorsaTools#114]
As the heading suggests, editing group components need to have the changes applied relatively to other components in the selected group

**Comment by zegreatclan** [comment]
I'm a little embarrassed with this request, the "convention" when using property grids and multiselect is to replicate the new value as is to all the selected components.

**Comment by PuReAdDicT** [comment]
I never meant to embarrass :)  As a Photoshop user, the main benefit of group selecting items is to be able to edit them relatively.  As it stands, there's no way of moving more than 1 item relative to another.  Committing stuff to widgets is too permanent, it reduces the chance of editing later (especially size). It's also very restricting in a "design" sense not to be able to move multiple items around without committing to a widget.  Maybe I'm trying to do things backwards by designing in DS, but to do anything complex, I have to know, to-the-pixel, where on the screen it is going to be located in advance of any photoshop work.  Dash elements made with multiple complex components need a way they can be moved around as a group without committing to a widget, unless there was a way to "break up" a widget maybe?

**Comment by zegreatclan** [comment]
hum , I think the key of the success is to handle better the locked components ;) 

you can move multiple items using mouse and keyboard, but if you selected them through the component list it's a bit hard to get back the focus to the editing windows and be able to move them using keyboard or mouse. Locked compoents won't be clickable and you will lose almost instantly your selelection.

Is that symptom correct ? 

for widgets you can change the size of it in the properties of the dash when editing it, it's not definitively locked up ;)

I'll try to think about a way to add what you request, because it's a good idea indeed, but I need to keep things understandable for everybody and respect the "UX" conventions at maximum ;)

**Comment by PuReAdDicT** [comment]
Yes that is correct.  However if one component is masking another, it's impossible to select that item in the edit window.  I have a tyre element where dirt linear gauge is shown over wear linear gauge, I have no way to selec it all and move it.
If it's possible to move with mouse and keyboard once the items are selected, then that is plenty.  Once I can select all the items!
Maybe if a 2nd tool was used for "selection"?  Where clicking and dragging it over a group of components selects everything in the area in the edit window, if its on top or underneath.  Or maybe a modifier key for the original tool to allow that function?

**Comment by zegreatclan** [comment]
I think we are close to something ;) in visual studio they use a key to get the focus back to the editing zone (F7) I use it often for the exact same problem, I think I will have to add the same solution ;) 

For the selection rectangle it's indeed something to add ;)

**Comment by PuReAdDicT** [comment]
Looking forward to even more complex designs in DS :)

**Comment by zegreatclan** [comment]
F7 is coming ;)

**Comment by PuReAdDicT** [comment]
WoOtz :D
