### ISSUE TITLE
List of Feature Request (a post for every single one would be silly)

### ISSUE THREAD

**Issue by manuelbiancolilla21** [zegreatclan/AssettoCorsaTools#188]
- Add car numbers for drivers ahead, behind and leaderboard
- Add car classes for drivers ahead, behind 
- Automatic Scrolling leaderboard
- Show YOUR CLASS only leaderboard, relatives
- Change Full car names with abbrevation (Porsche gt 991 rsr etc to 911, corvette c7r to c7r)
- Create new dashboard from selection and automatically crop it
- Try to implement what pit limiter speed is
- Try to implement Leaderboards real time gaps
- Add car class for me and opponents in available properties so that would be usable as ncalc

P.S Dont close this thread as i will use this one to update feature requests instead of opening a new one

**Comment by manuelbiancolilla21** [comment]
- Add computed fuel strategy like F1 2017 = a value that shows if you can finish the race and helps you knowing if you have to fuel save or not

**Comment by manuelbiancolilla21** [comment]
- Add self split and best split. Self split is updated every sector and gives your current time - self best lap time sector 1(+2+3) , Best split is with current session best lap. OPTIONAL Add best split for your class only

**Comment by manuelbiancolilla21** [comment]
- when in rf2 dev mode, you can see engine lifetime, is it possible to be shown on simhub too?
- can i use last lap fuel consumption instead of fuel per lap value to calculate laps remaining with fuel?

**Comment by zegreatclan** [comment]
Hi ! I lock this feature request, it's just impossible to follow, the one feature = one issue rule, allow me to follow in a clean way all the requests, in this form it's unusable.

**Comment by zegreatclan** [comment]
- Add car numbers for drivers ahead, behind and leaderboard -> Car numbers are not available in a separate manner in rf2
- Change Full car names with abbrevation (Porsche gt 991 rsr etc to 911, corvette c7r to c7r) -> I cant guess it :(
- Try to implement what pit limiter speed is -> Sadly it would be too random
- Add car class for me and opponents in available properties so that would be usable as ncalc -> Its available with drivercarclass function (available in ncalc too)
- when in rf2 dev mode, you can see engine lifetime, is it possible to be shown on simhub too? -> I've never seen this data in the plugin api
Create new dashboard from selection and automatically crop it -> https://github.com/zegreatclan/AssettoCorsaTools/issues/173
- Can i use last lap fuel consumption instead of fuel per lap value to calculate laps remaining with fuel?
The advantage of my way is that when you start to have data you keep it across sessions, last lap with always have a cold start, very annoying.

I created the following tickets : 
https://github.com/zegreatclan/AssettoCorsaTools/issues/192
https://github.com/zegreatclan/AssettoCorsaTools/issues/193
https://github.com/zegreatclan/AssettoCorsaTools/issues/194
https://github.com/zegreatclan/AssettoCorsaTools/issues/195
https://github.com/zegreatclan/AssettoCorsaTools/issues/196
