### ISSUE TITLE
Nextion Plugin: No more "inheritance" between physical and virtual screens definitions

### ISSUE THREAD

**Issue by TGD-Simracing** [zegreatclan/AssettoCorsaTools#216]
Suppose F is a physical screen and V1, V2 two virtual screens of F:

The definition:

[F.mycontrol]
txt = 'A'

should define the appearence of "mycontrol" for both V1 and V2

in the version 6.2.2 I have to repeat the definition for each virtual screen to have the same behavior. That is:

[V1.mycontrol]
txt = 'A'

[V2.mycontrol]
txt = 'A'

**Comment by zegreatclan** [comment]
I've took a look the previous behaviour was a bug fixed with the "goto" behaviour, the nextion implementation has never supported real inheritance, it was sending both instructions. And in this way click and such things were affected too making weird behaviours.

I have to rework it to get a real inheritance but it's not trivial

**Comment by zegreatclan** [comment]
I restored the previous behaviour, but it's not a real inheritance, so it must be used with caution, performances won't be the best.
