### ISSUE TITLE
Nextion bugged in latest versions.

### ISSUE THREAD

**Issue by FranVojvoda** [zegreatclan/AssettoCorsaTools#246]
It seems that most nextion projects (default projects f.e.) don't work fine in the latest versions, doesn't change the page (goto) or the data doesn't work properly. 
I have tested version 6.2.2 with my project and it works perfectly.

Arduino Micro + Nextion 4.3

6.2.2 Example
![11 5 18 19 31 office lens](https://user-images.githubusercontent.com/39198824/39938159-50cab890-5552-11e8-9731-0521e49cd1d6.jpg)
![11 5 18 19 32 office lens](https://user-images.githubusercontent.com/39198824/39938165-558a64e8-5552-11e8-8ec6-20989ea9cd8a.jpg)

**Comment by zegreatclan** [comment]
Indeed ! the fix is ready, but i've not tested everything, could I borrow you a few minutes and check using this version ? https://www.dropbox.com/s/7lo2v54k2z4lmde/HubPackage.6.03.9.zip?dl=0

**Comment by FranVojvoda** [comment]
It works, but not perfectly, unfortunately. When the screen change is frozen for a instant and shows the screen by default, without the data captured by simhub.

Uploading video -> https://www.youtube.com/watch?v=fIxK-5Qd96g

**Comment by zegreatclan** [comment]
Hum i see, so just a delay remaining, could i borrow your template so i can see exactly how you made it. It would be easier to understand what goes wrong.

When this will be fixed I promise I will never touch this again :D I had to rewrote it due to new leds support but it's hard to rewrite 2 years of cumulated work in a few weeks, these screens are hell :D

**Comment by zegreatclan** [comment]
Hi ! I made some additional changes to the version I published to racedepartment, now I only have a normal delay between the screen switch and the last data coming, indeed there was a big time wasting code which made the switch not smooth

**Comment by FranVojvoda** [comment]
Hi dude! Now the lag is low, practically not visible. Any recommendation to minimize it further? 
Thanks for your help!!!

**Comment by zegreatclan** [comment]
to reduce the effect, you can switch your components to global instead of local, like you did it (configured as local) they reset on screen change, it makes the reload more obvious. except that we are at the maximum of what the hardware can do, I think we are close or even better than before I broke everything :D

**Comment by FranVojvoda** [comment]
Many thanks! I will try it!!!
